# Generated by Django 2.1.4 on 2019-04-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_type', models.CharField(choices=[('EV', 'EV'), ('DVS', 'ДВС')], default=('EV', 'EV'), max_length=5)),
                ('veh_state', models.CharField(choices=[('hit', 'Битая'), ('fine', 'Целая')], default=('hit', 'Битая'), max_length=10)),
                ('tariff', models.CharField(choices=[('500', '500'), ('700', '700'), ('1000', '1000')], default=('700', '700'), max_length=5)),
                ('budget', models.CharField(max_length=20)),
                ('veh_model', models.CharField(max_length=50)),
                ('veh_comp', models.CharField(blank=True, max_length=10)),
                ('veh_year', models.CharField(blank=True, max_length=12)),
                ('veh_mileage', models.CharField(blank=True, max_length=20)),
                ('veh_color_in', models.CharField(blank=True, max_length=30)),
                ('veh_color', models.CharField(max_length=30)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
