# Generated by Django 2.1.4 on 2019-04-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhub_auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_task',
            name='veh_color',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
