# Generated by Django 2.1.4 on 2019-02-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_gdrive_vehicles_veh_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdrive_vehicles',
            name='veh_vin',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
