# Generated by Django 2.1.4 on 2019-02-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20190218_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdrive_vehicles',
            name='veh_folder',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
