# Generated by Django 2.1.4 on 2019-02-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_title', models.CharField(max_length=100)),
                ('veh_comp', models.CharField(blank=True, max_length=10)),
                ('veh_vin', models.CharField(max_length=30, unique=True)),
                ('veh_year', models.CharField(blank=True, max_length=12)),
                ('veh_mileage', models.CharField(blank=True, max_length=20)),
                ('veh_color_in', models.CharField(blank=True, max_length=30)),
                ('veh_color', models.CharField(max_length=30)),
                ('veh_price', models.CharField(max_length=10)),
                ('veh_photo', models.CharField(blank=True, max_length=250)),
                ('veh_battery', models.CharField(blank=True, max_length=10)),
                ('veh_info', models.CharField(blank=True, max_length=100)),
                ('veh_type', models.CharField(max_length=10)),
                ('veh_status', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
