# Generated by Django 2.1.4 on 2019-02-04 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('electrocars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
