# Generated by Django 2.1.4 on 2019-02-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrocars', '0003_auto_20190205_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='veh_photo',
            field=models.FileField(blank=True, upload_to='greenhub_remake/static/img/vehicles/'),
        ),
    ]
