# Generated by Django 2.1.4 on 2019-02-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrocars', '0004_auto_20190205_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='veh_photo',
            field=models.FileField(blank=True, upload_to='static/img/vehicles/'),
        ),
    ]
