# Generated by Django 2.1.4 on 2019-02-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electrocars', '0005_auto_20190205_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_photos',
            name='veh_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='electrocars.Vehicle'),
        ),
    ]
