# Generated by Django 2.1.4 on 2019-02-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrocars', '0007_vehicle_photos_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='veh_photo',
            field=models.FileField(blank=True, upload_to='static/img/vehicles/%Y/%m/%d/'),
        ),
    ]
