# Generated by Django 2.1.4 on 2019-07-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrocars', '0013_auto_20190411_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_model', models.CharField(default='empty', max_length=100)),
                ('veh_photo', models.FileField(blank=True, max_length=500, upload_to='')),
                ('veh_year', models.CharField(default='0', max_length=10)),
                ('veh_mileage', models.CharField(default='0', max_length=10)),
                ('veh_color_in', models.CharField(default='empty', max_length=20)),
                ('vah_color', models.CharField(default='empty', max_length=20)),
                ('veh_price', models.CharField(default='0', max_length=10)),
                ('veh_type', models.CharField(default='empty', max_length=20)),
                ('veh_status', models.CharField(default='empty', max_length=20)),
                ('record_status', models.BooleanField(default=True)),
                ('veh_incomming_date', models.CharField(default='empty', max_length=20)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
