# Generated by Django 2.1.4 on 2019-06-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm_clients',
            name='client_type',
            field=models.CharField(default='empty', max_length=50, null=True),
        ),
    ]
