# Generated by Django 2.1.4 on 2019-02-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=50, null=True)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_stage', models.CharField(blank=True, max_length=20, null=True)),
                ('client_status', models.BooleanField()),
                ('client_join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
