# Generated by Django 2.1.4 on 2019-02-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients_main',
            name='client_phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
