# Generated by Django 2.1.4 on 2019-02-04 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20190204_2229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients_main',
            new_name='Clients',
        ),
    ]
